// CONTEO DE  MAYUSCULAS Y MINUSCULAS 
function conteo(obj){
var mayus = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ";
var minus = "abcdefghijklmnñopqrstuvwxyz";
for (let i=0; i<mayus.length; i++){
  if(obj[i]==mayus[i]){
    console.log(`tiene ${conteo} palabras`)
  }
  for(let i=0; i<mimus.length; i++) {
    if(obj[i]==minus[i]){
      
   console.log(`tiene ${conteo} palabras`)
    } 
  }
 }
}
var obj = new conteo(`HOLA`);
obj();
console.log(obj())

// TABLA DE MULTIPLICAR 
//   function tabla(n) {
//     for (let i = 1; i <= 10; i++) {
//       multi = n * i;
//       console.log(n + "x" + i + "=" + multi);
//     }
//   }
// console.log(tabla(7));

//Leer dos vectores.
//Hallar de cada uno del promedio y retornar el vector con mayor promedio


//CONTEO REPETICION DE UN NUMERO 
// var num=3
// var array = ['1','3','2','6','2','3','1','1'];

// var cont = 0
// for(var i = 0 ; i < array.length ; i++){
//   if (num==array[i]){
//     cont= cont+1
//   }
// }
// console.log(cont());

//Leer un arreglo numérico y retornar desviación estandar

